export const firebaseConfig = {
  // apiKey: process.env.APIKEY,
  // authDomain: process.env.AUTHDOMAIN,
  // projectId: process.env.PROJECTID,
  // storageBucket: process.env.STORAGEBUCKET,
  // messagingSenderId: process.env.MESSAGINGSENDERID,
  // appId: process.env.APPID,
  // measurementId: process.env.MEASUREMENTID,
  apiKey: "AIzaSyCdYWbMhEIaBZP_H1LFvFijod0xq0T2IbU",
  clientEmail: "isaac.pak.2024@gmail.com",
  authDomain: "wooweb-2e58a.firebaseapp.com",
  projectId: "wooweb-2e58a",
  storageBucket: "wooweb-2e58a.appspot.com",
  messagingSende: "972843793573",
  appId: "1:972843793573:web:42d7d9cd5e211b28bb614c",
  measurementId: "G-VN37ZHEMS2",
};
